### ISSUE TITLE
`env.render(mode='rgb_array')` returns `none`

### ISSUE THREAD

**Issue by fyqqyf** [Farama-Foundation/Gymnasium-Robotics#131]
I’m trying to run MaMuJoCo on a headless server, but when I use `env.render(mode='rgb_array')`, it returns `none`. I don’t understand why. 
Could you please help me? Thank you!

**Comment by rodrigodelazcano** [comment]
Does this only happen in the headless server? @Kallinteris-Andreas do you have any clue on what could be the issue. I'll have a look at it as well

**Comment by rodrigodelazcano** [comment]
The issue is that `ma-mujoco` environments are supposed to follow the PettingZoo API. However, since this is achieved by wrapping the MuJoCo Gymnasium environments, the renderer is initialized as if it belonged to the Gymnasium API ([passing the `render_mode` when the environment is initialized](https://gymnasium.farama.org/api/env/#gymnasium.Env.render_mode)). We should change this to make it fully compatible with PettingZoo. @Kallinteris-Andreas do you have the time to work on this feature?

Also, @fyqqyf in the mean time could you try if initializing the renderer as follows works for your use case:

```python
from gymnasium_robotics import mamujoco_v0

env = mamujoco_v0.parallel_env("Hopper", "3x1", render_mode='"rgb_array")

env.reset()
env.render()

```

**Comment by Kallinteris-Andreas** [comment]
@fyqqyf the issue if fixed now, feel free to try it
